Update readme v2
yoou21/diary-app pull request #2
Opened 2024-11-16 03:15 UTC by yoou21

READMEを新規で作成し、README専用 PullRequestフォーマットを記入しております。
必要な修正や補足案があればご指摘ください。

2024-11-16 06:16 UTC, Mariko222 commented
ご提出ありがとうございます。
以下、気になった点のコメントになります。
***
> 感情データを活用して、ユーザーの内面を理解し、ポジティブな変化を促したい。

- 感情データはどのような形で収集し、ユーザーへ還元される想定でしょうか？
感情ヒートマップの導入が目標達成にどのように作用するのかが不明瞭なので、具体的なイメージや例を想定されてましたら教えていただきたいです。
> 振り返り機能で達成感を強調し、次の挑戦へのモチベーションを提供

- こちらもどのように達成感を強調して次に繋げるのか、具体的なイメージや例を想定されてましたら教えていただきたいです。

2024-11-16 08:33 UTC, yoou21 commented
READMEの内容更新: 感情データの活用方法とユーザー還元の具体例を追記しました。
他に改善した方が良い点がありましたら、ご連絡お願いします。

2024-11-17 04:45 UTC, tarakish requested changes
修正確認しました。以下コメントです！

---

- サービスの差別化ポイント
> 本アプリでは、感情と進捗を同時に管理することで、ユーザーが達成感を得やすくします。

こちら現状の説明では、感情と進捗を同時に管理すること→達成感を得られたり、目標達成に活用する部分がまだ少し不明瞭に感じました。
具体例を2つ程度挙げていただけますか？

2024-11-17 08:44 UTC, yoou21 commented
READMEのサービスの差別化ポイントを更新しました。
他に改善した方が良い点がありましたら、ご連絡お願いします。

2024-11-18 04:13 UTC, ippei-shimizu commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びREADME.mdへの反映をお願いします。
...

- ユーザーによって使用するポジティブ・ネガティブの言葉が違うことが想定されます。その場合の、ポジティブ・ネガティブの判定はどのように行いますか？

2024-11-18 13:30 UTC, yoou21 commented
ポジティブ・ネガティブの判定に関して更新しました。ご確認のほどよろしくお願いいたします。

2024-11-19 03:42 UTC, TakenakaEri commented
LGMTです！

MVPリリースの際の実装内容が本リリースでも良いのかな？と思う部分もありますが、一旦このまま進んでください。
（issueの時やのちのち調整できると思います）

次も頑張ってください！

2024-11-19 12:22 UTC, merged